First pythondialog release minus the changes from Sultanbek Tezadov
* Repository created in August 2013 to help with comparing between the
various pythondialog releases and with further development.

* This commit corresponds to pythondialog 1.0 as distributed at
<http://sourceforge.net/projects/pythondialog/> (which
<http://pythondialog.sourceforge.net/> links to), with the following
exception: I (Florent Rougon) temporarily removed the gauge-related
changes that are clearly from Sultanbek Tezadov according to the
comments in dialog.py. These changes will be added to the repository in
the next commit with proper authorship metadata.

* The date is approximate: it is again based on the comments in
dialog.py, indicating that Sultanbek Tezadov's changes were contributed
in July 2000.

* To the best of my knowledge, most of the actual code added in this
commit was written by Robb Shecter, hence the authorship metadata.